<?php

namespace AppBundle\Repository;

/**
 * OrgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param bool $keyByName
     * @return array
     */
    public function getTags($keyByName = false)
    {
        $tags = [
            'assistive' => "Assistive technology",
            'audiovisual' => "Audio visual equipment",
            'education' => "Educational equipment",
            'house' => "Home & Garden",
            'kitchen' => "Kitchen / catering",
            'repair' => "Repair cafe",
            'slings' => "Slings / baby carriers",
            'nappies' => "Nappies",
            'toys' => "Toys",
            'plant' => "Tools/plant (commercial)",
            'tools' => "Tools (personal/DIY)",
            'sports' => "Sporting goods",
            'electronics' => "Electronic equipment",
        ];
        if ($keyByName == true) {
            $tags = array_flip($tags);
        }
        return $tags;
    }
}
